# Generated by Django 5.1.7 on 2025-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('installed', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=10)),
            ],
        ),
    ]
