# Generated by Django 5.1.7 on 2025-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
    ]
