# Generated by Django 5.1.7 on 2025-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0003_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='installed',
            new_name='is_installed',
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
