# Generated by Django 5.1.7 on 2025-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0004_rename_installed_module_is_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='latest_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
