# Generated by Django 5.1.7 on 2025-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0005_module_latest_version_alter_module_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='latest_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=10, null=True),
        ),
    ]
