# Generated by Django 5.1.7 on 2025-03-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0006_alter_module_latest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='latest_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
